port: 80
oauth:
  accessTokenUri: 'https://discord.com/api/oauth2/token'
  authorizationUri: 'https://discord.com/api/oauth2/authorize'
  redirectUri: 'http://127.0.0.1/oauth/callback'
  clientId: ''
  clientSecret: ''
  scopes: [identify, guild]
database:
  user: ''
  password: ''
  address: ''
  port: 5432
  database: postgres
